name: db
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  dart_frog: ^1.1.0
  json_annotation: ^4.9.0
  orm: ^5.0.4
  # path: ^1.8.0

dev_dependencies:
  # export PATH="$PATH":"$HOME/.pub-cache/bin"
  #run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^6.0.0